# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-11-23 15:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('Last one', 'Last one'), ('Low stock', 'Low stock'), ('More than n copies available', 'More than n copies available')], default='REGULAR', max_length=50, null=True),
        ),
    ]
