# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-11-23 16:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20191123_1602'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='variant',
        ),
        migrations.DeleteModel(
            name='ProductVariant',
        ),
    ]
